In [19]:
import random
import pandas as pd
import numpy as np

In [20]:
load_o = pd.read_csv("demand_30_raw.csv")
#load_o = pd.read_csv("DAY_AHEAD_regional_Load.csv")
load_dis = pd.read_csv("load_d.csv")

In [21]:
load_o['Nday'] = load_o['Day']

In [22]:
months = load_o.Month.unique()
months = months[1:]
db = 0
for m in months:
    db += max(load_o[load_o.Month == (m-1)].Day)
    load_o.loc[load_o.Month == m,'Nday'] = load_o[load_o.Month == (m)].Day + db

In [23]:
load_o.Nday =  "d" + load_o.Nday.astype(str)

In [24]:
load_n = pd.DataFrame(index = load_o.index)

In [25]:
load_n['Day'] = load_o.Nday
#load_n["dot1"] = len(load_n)*["."]
load_n['Time'] = "t" + load_o.Period.astype(str)
load_n = pd.concat([load_n,pd.DataFrame(columns = load_dis.columns)],sort=False)

In [26]:
np.random.seed(100)
rmat = pd.DataFrame(data = ((np.random.rand(load_n.shape[0],load_dis.shape[1])*2-1)*0.005),index = load_o.index, columns = load_dis.columns)

In [27]:
load_n.loc[:,'s101':'s120'] = (rmat.loc[:,'s101':'s120']+1).mul(load_o.loc[:,'1'], axis =0)

In [28]:
load_n.loc[:,'s201':'s220'] = (rmat.loc[:,'s201':'s220']+1).mul(load_o.loc[:,'2'], axis =0)

In [29]:
load_n.loc[:,'s301':'s320'] = (rmat.loc[:,'s301':'s320']+1).mul(load_o.loc[:,'3'], axis =0)

In [30]:
load_n.loc[:,'s101':'s320'] = load_n.loc[:,'s101':'s320'].mul(load_dis.loc[0,:], axis =1)

In [31]:
a1 = 't' + pd.Series(range(1,73)).astype(str)

In [32]:
#load_n_t1 = load_n[load_n.Day == 'd1']
#load_n_t1 = load_n_t1[load_n_t1.Time.isin(a1)]

In [33]:
#load_n = load_n.drop(['dot1'],axis = 1)
lo_out = pd.melt(load_n,id_vars=['Day','Time'])
#lo_out1 = pd.melt(load_n_t1,id_vars=['Day','Time'])

In [34]:
#lo_out1['dot1'] = len(lo_out1)*["."]
#lo_out1['dot2'] = len(lo_out1)*["."]
lo_out['dot1'] = len(lo_out)*["."]
lo_out['dot2'] = len(lo_out)*["."]

In [35]:
#lo_out.sort_values(by=['Day'])
lo_out

         Day Time variable    value dot1 dot2
0         d1   t1     s101  34.4782    .    .
1         d1   t2     s101  34.5257    .    .
2         d1   t3     s101  34.3881    .    .
3         d1   t4     s101  34.6305    .    .
4         d1   t5     s101  34.9599    .    .
5         d1   t6     s101  35.0895    .    .
6         d1   t7     s101  35.5918    .    .
7         d1   t8     s101  36.6476    .    .
8         d1   t9     s101  38.6852    .    .
9         d1  t10     s101  40.8875    .    .
10        d1  t11     s101  44.0218    .    .
11        d1  t12     s101  45.7463    .    .
12        d1  t13     s101  47.1096    .    .
13        d1  t14     s101  47.2587    .    .
14        d1  t15     s101  46.5665    .    .
15        d1  t16     s101  44.8365    .    .
16        d1  t17     s101  43.5583    .    .
17        d1  t18     s101  42.3893    .    .
18        d1  t19     s101  41.5859    .    .
19        d1  t20     s101  41.1129    .    .
20        d1  t21     s101  40.5979    .    .
21        d1  t22     s101  40.2054    .    .
22        d1  t23     s101  39.7077    .    .
23        d1  t24     s101  39.2705    .    .
24        d1  t25     s101  38.8372    .    .
25        d1  t26     s101  38.4588    .    .
26        d1  t27     s101  38.3976    .    .
27        d1  t28     s101  37.9804    .    .
28        d1  t29     s101  38.1055    .    .
29        d1  t30     s101  38.0731    .    .
...      ...  ...      ...      ...  ...  ...
895938  d366  t19     s320  68.4269    .    .
895939  d366  t20     s320  69.1214    .    .
895940  d366  t21     s320  70.5766    .    .
895941  d366  t22     s320  70.4727    .    .
895942  d366  t23     s320  70.6065    .    .
895943  d366  t24     s320  70.0527    .    .
895944  d366  t25     s320    70.18    .    .
895945  d366  t26     s320  70.1635    .    .
895946  d366  t27     s320  69.5114    .    .
895947  d366  t28     s320  69.1802    .    .
895948  d366  t29     s320  69.4193    .    .
895949  d366  t30     s320  69.6217    .    .
895950  d366  t31     s320   68.846    .    .
895951  d366  t32     s320  68.7512    .    .
895952  d366  t33     s320   68.306    .    .
895953  d366  t34     s320  71.3987    .    .
895954  d366  t35     s320  77.1839    .    .
895955  d366  t36     s320  78.6522    .    .
895956  d366  t37     s320  78.7731    .    .
895957  d366  t38     s320  78.0682    .    .
895958  d366  t39     s320  77.1397    .    .
895959  d366  t40     s320  76.4907    .    .
895960  d366  t41     s320  75.2735    .    .
895961  d366  t42     s320  74.8833    .    .
895962  d366  t43     s320  72.6324    .    .
895963  d366  t44     s320  70.2656    .    .
895964  d366  t45     s320  67.2408    .    .
895965  d366  t46     s320  64.5907    .    .
895966  d366  t47     s320  61.8132    .    .
895967  d366  t48     s320  59.6496    .    .

[895968 rows x 6 columns]

In [36]:
lo_out = lo_out[['Day','dot1','Time','dot2','variable','value']]

In [60]:
#lo_out1 = lo_out1[['Day','dot1','Time','dot2','variable','value']]

In [61]:
#lo_out1.to_csv("demand_rtt.csv",index = False,header = False,na_rep="")

In [37]:

#load_n.to_csv("demand_rt.csv",index=False,header=True,na_rep="")
#lo_out.to_csv("demand_da2.csv",index = False,header = False,na_rep="")
lo_out.to_csv("demand_rtf.csv",index = False,header = False,na_rep="")